---
argocd: 
  enabled: &argo true

kafka-cluster:
  argocd: 
    enabled: *argo
    syncwave: "-2"

kafka-topics:
  argocd: 
    enabled: *argo
    syncwave: "-2"

retail-db:
  argocd: 
    enabled: *argo
    syncwave: "-2"

cashback-db:
  argocd: 
    enabled: *argo
    syncwave: "-2"

elasticsearch:
  argocd:
    enabled: *argo
    syncwave: "-2"
  credentials:
    username: cashback
    password: cashback

kafka-connect:
  argocd:
    enabled: *argo
    syncwave: "-1"
  replicationFactor: 3
  bootstrapServers: "kafka-kafka-bootstrap:9092"
  authentication:
    enabled: false
  tls: false

elastic-connector:
  kafka:
    bootstrapServer: "kafka-kafka-bootstrap:9092"
    securityProtocol: ""
    saslMechanism: ""
  elasticsearch:
    hosts: retail-es-http:9200
    username: cashback
    password: cashback
