---
argocd: 
  enabled: &argo true

kafkaBootstrapServer: &kafkaBootstrapServer "kafka-kafka-bootstrap:9092"

kafka-cluster:
  argocd: 
    enabled: *argo
    syncwave: "-2"

kafka-topics:
  argocd: 
    enabled: *argo
    syncwave: "-2"

retail-db:
  argocd: 
    enabled: *argo
    syncwave: "-2"

cashback-db:
  argocd: 
    enabled: *argo
    syncwave: "-2"
  pgsql:
    user: cashback
    password: cashback
    adminPassword: password
    database: cashback

elasticsearch:
  argocd:
    enabled: *argo
    syncwave: "-2"
  credentials:
    username: cashback
    password: cashback

kafka-connect:
  argocd:
    enabled: *argo
    syncwave: "-1"
  replicationFactor: 3
  bootstrapServers: *kafkaBootstrapServer
  authentication:
    enabled: false
  tls: false

elastic-connector:
  kafka:
    bootstrapServer: *kafkaBootstrapServer
    securityProtocol: ""
    saslMechanism: ""
  elasticsearch:
    hosts: retail-es-http:9200
    username: cashback
    password: cashback

sales-streams:
  kafka:
    bootstrapServer: *kafkaBootstrapServer
    securityProtocol: ""
    saslMechanism: ""
    streams:
      replicationFactor: 3

cashback-connector:
  kafka:
    bootstrapServer: *kafkaBootstrapServer
    securityProtocol: ""
    saslMechanism: ""
  postgresql:
    host: cashback-db
    username: cashback
    password: cashback
    database: cashback

cashback-service:
  kafka:
    bootstrapServer: *kafkaBootstrapServer
    securityProtocol: ""
    saslMechanism: ""
  postgresql:
    host: cashback-db
    username: cashback
    password: cashback
    database: cashback

cashback-service-ui:
  postgresql:
    host: cashback-db
    username: cashback
    password: cashback
    database: cashback

search-service:
  elasticsearch:
    hosts: retail-es-http:9200
    username: cashback
    password: cashback 
