---
argocd: 
  enabled: &argo true

kafka-cluster:
  argocd: 
    enabled: *argo
    syncwave: "-2"

kafka-topics:
  argocd: 
    enabled: *argo
    syncwave: "-2"

retail-db:
  argocd: 
    enabled: *argo
    syncwave: "-2"

cashback-db:
  argocd: 
    enabled: *argo
    syncwave: "-2"

elasticsearch:
  argocd:
    enabled: *argo
    syncwave: "-2"
